### ISSUE TITLE
Links Redes Sociais 

### ISSUE THREAD

**Issue by GlauciaRangel** [goblockchain/goblockchain.github.io#28]
![image](https://user-images.githubusercontent.com/32552179/48300815-ba01b180-e4ca-11e8-8127-95612c80c04c.png)

Os links no rodape para as redes sociais estão indo p lugar errado (está descolado)

**Comment by guisantos** [comment]
Estou trabalhando nessa issue

**Comment by guisantos** [comment]
Corrigido no PR [#31] (https://github.com/goblockchain/goblockchain.github.io/pull/31)
